# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_profilefrompoints.ui'
#
# Created: Mon Oct 27 09:50:03 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ProfilefromPoints(object):
    def setupUi(self, ProfilefromPoints):
        ProfilefromPoints.setObjectName(_fromUtf8("ProfilefromPoints"))
        ProfilefromPoints.resize(887, 695)
        ProfilefromPoints.setSizeGripEnabled(True)
        ProfilefromPoints.setModal(False)
        self.gridLayout_2 = QtGui.QGridLayout(ProfilefromPoints)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.layoutPlot = QtGui.QGridLayout()
        self.layoutPlot.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.layoutPlot.setObjectName(_fromUtf8("layoutPlot"))
        self.mpltoobar = QtGui.QWidget(ProfilefromPoints)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpltoobar.sizePolicy().hasHeightForWidth())
        self.mpltoobar.setSizePolicy(sizePolicy)
        self.mpltoobar.setMaximumSize(QtCore.QSize(100, 100))
        self.mpltoobar.setObjectName(_fromUtf8("mpltoobar"))
        self.layoutPlot.addWidget(self.mpltoobar, 1, 0, 1, 1)
        self.widgetPlot = QtGui.QWidget(ProfilefromPoints)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.widgetPlot.sizePolicy().hasHeightForWidth())
        self.widgetPlot.setSizePolicy(sizePolicy)
        self.widgetPlot.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widgetPlot.setObjectName(_fromUtf8("widgetPlot"))
        self.layoutPlot.addWidget(self.widgetPlot, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.layoutPlot, 0, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(ProfilefromPoints)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.uSelectedPoints = QtGui.QCheckBox(self.groupBox)
        self.uSelectedPoints.setObjectName(_fromUtf8("uSelectedPoints"))
        self.gridLayout.addWidget(self.uSelectedPoints, 2, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.groupBox)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 4, 1, 1, 1)
        self.utabWidget = QtGui.QTabWidget(self.groupBox)
        self.utabWidget.setObjectName(_fromUtf8("utabWidget"))
        self.utabCreateLine = QtGui.QWidget()
        self.utabCreateLine.setObjectName(_fromUtf8("utabCreateLine"))
        self.formLayout_2 = QtGui.QFormLayout(self.utabCreateLine)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_3 = QtGui.QLabel(self.utabCreateLine)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.uOrderField = QtGui.QComboBox(self.utabCreateLine)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uOrderField.sizePolicy().hasHeightForWidth())
        self.uOrderField.setSizePolicy(sizePolicy)
        self.uOrderField.setMinimumSize(QtCore.QSize(200, 0))
        self.uOrderField.setObjectName(_fromUtf8("uOrderField"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.uOrderField)
        self.label_4 = QtGui.QLabel(self.utabCreateLine)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.uOrder = QtGui.QComboBox(self.utabCreateLine)
        self.uOrder.setObjectName(_fromUtf8("uOrder"))
        self.uOrder.addItem(_fromUtf8(""))
        self.uOrder.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.uOrder)
        self.utabWidget.addTab(self.utabCreateLine, _fromUtf8(""))
        self.utabExistingLine = QtGui.QWidget()
        self.utabExistingLine.setObjectName(_fromUtf8("utabExistingLine"))
        self.formLayout_3 = QtGui.QFormLayout(self.utabExistingLine)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_5 = QtGui.QLabel(self.utabExistingLine)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.uLineLayer = QtGui.QComboBox(self.utabExistingLine)
        self.uLineLayer.setMinimumSize(QtCore.QSize(200, 0))
        self.uLineLayer.setObjectName(_fromUtf8("uLineLayer"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.uLineLayer)
        self.label_6 = QtGui.QLabel(self.utabExistingLine)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.uBuffer = QtGui.QLineEdit(self.utabExistingLine)
        self.uBuffer.setAutoFillBackground(True)
        self.uBuffer.setObjectName(_fromUtf8("uBuffer"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.uBuffer)
        self.uSelectedLine = QtGui.QCheckBox(self.utabExistingLine)
        self.uSelectedLine.setChecked(False)
        self.uSelectedLine.setObjectName(_fromUtf8("uSelectedLine"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.uSelectedLine)
        self.utabWidget.addTab(self.utabExistingLine, _fromUtf8(""))
        self.gridLayout.addWidget(self.utabWidget, 0, 1, 4, 1)
        self.uCopytoClip = QtGui.QPushButton(self.groupBox)
        self.uCopytoClip.setEnabled(False)
        self.uCopytoClip.setObjectName(_fromUtf8("uCopytoClip"))
        self.gridLayout.addWidget(self.uCopytoClip, 3, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.uPointLayer = QtGui.QComboBox(self.groupBox)
        self.uPointLayer.setMinimumSize(QtCore.QSize(200, 0))
        self.uPointLayer.setObjectName(_fromUtf8("uPointLayer"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.uPointLayer)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.uZfield = QtGui.QComboBox(self.groupBox)
        self.uZfield.setMinimumSize(QtCore.QSize(200, 0))
        self.uZfield.setObjectName(_fromUtf8("uZfield"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.uZfield)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.uprogressBar = QtGui.QProgressBar(self.groupBox)
        self.uprogressBar.setMaximum(100)
        self.uprogressBar.setProperty("value", 0)
        self.uprogressBar.setObjectName(_fromUtf8("uprogressBar"))
        self.gridLayout.addWidget(self.uprogressBar, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 2)

        self.retranslateUi(ProfilefromPoints)
        self.utabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ProfilefromPoints.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ProfilefromPoints.reject)
        QtCore.QMetaObject.connectSlotsByName(ProfilefromPoints)
        ProfilefromPoints.setTabOrder(self.uOrderField, self.uOrder)
        ProfilefromPoints.setTabOrder(self.uOrder, self.uLineLayer)
        ProfilefromPoints.setTabOrder(self.uLineLayer, self.uBuffer)

    def retranslateUi(self, ProfilefromPoints):
        ProfilefromPoints.setWindowTitle(_translate("ProfilefromPoints", "ProfilefromPoints", None))
        self.groupBox.setTitle(_translate("ProfilefromPoints", "Options", None))
        self.uSelectedPoints.setText(_translate("ProfilefromPoints", "Use only selected points", None))
        self.label_3.setText(_translate("ProfilefromPoints", "Order field", None))
        self.label_4.setText(_translate("ProfilefromPoints", "Sort order", None))
        self.uOrder.setItemText(0, _translate("ProfilefromPoints", "Ascending", None))
        self.uOrder.setItemText(1, _translate("ProfilefromPoints", "Descending", None))
        self.utabWidget.setTabText(self.utabWidget.indexOf(self.utabCreateLine), _translate("ProfilefromPoints", "Create profile line", None))
        self.label_5.setText(_translate("ProfilefromPoints", "Line layer", None))
        self.label_6.setText(_translate("ProfilefromPoints", "Buffer distance from line (line layer units)", None))
        self.uBuffer.setText(_translate("ProfilefromPoints", "1000", None))
        self.uSelectedLine.setText(_translate("ProfilefromPoints", "Use selected line only", None))
        self.utabWidget.setTabText(self.utabWidget.indexOf(self.utabExistingLine), _translate("ProfilefromPoints", "Use existing line", None))
        self.uCopytoClip.setText(_translate("ProfilefromPoints", "Copy Station and Elevation to Clipboard", None))
        self.label.setText(_translate("ProfilefromPoints", "Point layer", None))
        self.label_2.setText(_translate("ProfilefromPoints", "Elevation field", None))

